/**
 * Auto-generated by materialize-custom-components.mjs
 * DO NOT EDIT MANUALLY — re-run materialization to update.
 */

import React from "react";
import {
  booleanField,
  listField,
  selectField,
  textField,
  textareaField,
} from "@/puck/field-adapters";
import * as TemplateExclusiveAudezeHomeHomeNavigationNavbarPrimaryBlockModule from "@/components/blocks/navbar/block";
import * as TemplateExclusiveAudezeHomeHomeHeroHerosplitPrimaryBlockModule from "@/components/blocks/hero-split/block";
import * as TemplateExclusiveAudezeHomeHomeApproachFeaturegridPrimaryBlockModule from "@/components/blocks/feature-grid/block";
import * as TemplateExclusiveAudezeHomeHomeSocialproofTestimonialsgridPrimaryBlockModule from "@/components/blocks/testimonials-grid/block";
import * as TemplateExclusiveAudezeHomeHomeCtaLeadcapturectaPrimaryBlockModule from "@/components/blocks/lead-capture-cta/block";
import * as TemplateExclusiveAudezeHomeHomeFooterFooterPrimaryBlockModule from "@/components/blocks/footer/block";
import * as TemplateExclusiveAudezeHomeCollectionsAccessoriesNavigationNavbarPrimaryBlockModule from "@/components/blocks/navbar/block";
import * as TemplateExclusiveAudezeHomeCollectionsAccessoriesHeroHerosplitPrimaryBlockModule from "@/components/blocks/hero-split/block";
import * as TemplateExclusiveAudezeHomeCollectionsAccessoriesCtaLeadcapturectaPrimaryBlockModule from "@/components/blocks/lead-capture-cta/block";
import * as TemplateExclusiveAudezeHomeCollectionsAccessoriesFooterFooterPrimaryBlockModule from "@/components/blocks/footer/block";

const resolveBlockComponent = (
  moduleExports: Record<string, unknown>,
  modulePath: string
): React.ComponentType<any> => {
  const directDefault = (moduleExports as { default?: unknown }).default;
  if (typeof directDefault === "function") {
    return directDefault as React.ComponentType<any>;
  }

  for (const candidate of Object.values(moduleExports || {})) {
    if (typeof candidate === "function") {
      return candidate as React.ComponentType<any>;
    }
  }

  console.warn(`[config.generated] unable to resolve component export from ${modulePath}`);
  return () => null;
};

const renderBlock = (Block: React.ComponentType<any>) => (props: any) =>
  React.createElement(Block, props);

export const generatedComponents: Record<string, any> = {
    TemplateExclusiveAudezeHomeHomeNavigationNavbarPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeHomeNavigationNavbarPrimaryBlockModule, "TemplateExclusiveAudezeHomeHomeNavigationNavbarPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeHomeNavigationNavbarPrimary-1",
            "variant": "withDropdown",
            "sticky": true,
            "paddingY": "sm",
            "maxWidth": "xl",
            "logo": "Audeze Headphones",
            "links": [
                  {
                        "label": "Home",
                        "href": "/",
                        "variant": "link"
                  },
                  {
                        "label": "Audeze",
                        "href": "/collections/accessories",
                        "variant": "link",
                        "children": [
                              {
                                    "label": "Angie Randisi",
                                    "href": "/blogs/audeze-artists/angie-randisi"
                              }
                        ]
                  }
            ],
            "ctas": [
                  {
                        "label": "Explore",
                        "href": "/blogs/audeze-artists/angie-randisi",
                        "variant": "primary"
                  }
            ],
            "menuStyle": "image_text",
            "multiLevel": true
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        sticky: booleanField("Sticky"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        logo: textField("Logo"),
        menuStyle: textField("Menustyle"),
        multiLevel: booleanField("Multilevel"),
      },
    },
    TemplateExclusiveAudezeHomeHomeHeroHerosplitPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeHomeHeroHerosplitPrimaryBlockModule, "TemplateExclusiveAudezeHomeHomeHeroHerosplitPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeHomeHeroHerosplitPrimary-1",
            "mediaPosition": "right",
            "paddingY": "lg",
            "headingSize": "md",
            "maxWidth": "xl",
            "title": "Welcome to Uncompromised Audio",
            "subtitle": "PRODUCTS",
            "ctas": [
                  {
                        "label": "Explore",
                        "href": "/blogs/audeze-artists/angie-randisi",
                        "variant": "primary"
                  }
            ],
            "heroSlides": [
                  {
                        "src": "https://www.audeze.com/cdn/shop/files/Audeze_A_410x.svg?v=1726000216",
                        "mobileSrc": "https://www.audeze.com/cdn/shop/files/Audeze_A_410x.svg?v=1726000216",
                        "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero slide 1",
                        "label": "Slide 1"
                  },
                  {
                        "src": "https://www.audeze.com/cdn/shop/files/SLAM2_2000x.jpg?v=1744253058",
                        "mobileSrc": "https://www.audeze.com/cdn/shop/files/SLAM2_2000x.jpg?v=1744253058",
                        "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero slide 2",
                        "label": "Slide 2"
                  },
                  {
                        "src": "https://www.audeze.com/cdn/shop/files/Audeze_Explosion_5_2000x_megamenu_2000x.png?v=1648507119",
                        "mobileSrc": "https://www.audeze.com/cdn/shop/files/Audeze_Explosion_5_2000x_megamenu_2000x.png?v=1648507119",
                        "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero slide 3",
                        "label": "Slide 3"
                  },
                  {
                        "src": "https://www.audeze.com/cdn/shop/files/LCD-4z___Joe_L_2000x_megamenu_2000x.png?v=1648507119",
                        "mobileSrc": "https://www.audeze.com/cdn/shop/files/LCD-4z___Joe_L_2000x_megamenu_2000x.png?v=1648507119",
                        "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero slide 4",
                        "label": "Slide 4"
                  },
                  {
                        "src": "https://www.audeze.com/cdn/shop/files/Driver-Explosion-Image_2000x_megamenu_2000x.png?v=1648507119",
                        "mobileSrc": "https://www.audeze.com/cdn/shop/files/Driver-Explosion-Image_2000x_megamenu_2000x.png?v=1648507119",
                        "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero slide 5",
                        "label": "Slide 5"
                  },
                  {
                        "src": "https://www.audeze.com/cdn/shop/files/Angie_2000x.jpg?v=1764708774",
                        "mobileSrc": "https://www.audeze.com/cdn/shop/files/Angie_2000x.jpg?v=1764708774",
                        "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero slide 6",
                        "label": "Slide 6"
                  }
            ],
            "heroCarouselAutoplayMs": 4500,
            "background": "image",
            "backgroundMedia": {
                  "kind": "image",
                  "src": "https://www.audeze.com/cdn/shop/files/Audeze_A_410x.svg?v=1726000216",
                  "alt": "Audeze Headphones | Uncompromised Audio | Planar Magnetic Technology hero background"
            },
            "backgroundOverlay": "rgba(4, 14, 36, 0.58)"
      },
      fields: {
        id: textField("Id"),
        mediaPosition: textField("Mediaposition"),
        paddingY: textField("Paddingy"),
        headingSize: textField("Headingsize"),
        maxWidth: textField("Maxwidth"),
        title: textField("Title"),
        subtitle: textField("Subtitle"),
        heroCarouselAutoplayMs: textField("Herocarouselautoplayms"),
        background: textField("Background"),
        backgroundOverlay: textField("Backgroundoverlay"),
      },
    },
    TemplateExclusiveAudezeHomeHomeApproachFeaturegridPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeHomeApproachFeaturegridPrimaryBlockModule, "TemplateExclusiveAudezeHomeHomeApproachFeaturegridPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeHomeApproachFeaturegridPrimary-1",
            "variant": "3col",
            "paddingY": "lg",
            "maxWidth": "xl",
            "title": "Gaming",
            "subtitle": "Professional Audio",
            "items": [
                  {
                        "title": "PRODUCTS",
                        "desc": "PRODUCTS",
                        "description": "PRODUCTS",
                        "icon": "layers",
                        "image": {
                              "src": "/assets/template-factory/audeze-home/slices/desktop-approach.png",
                              "alt": "PRODUCTS"
                        },
                        "imageSrc": "/assets/template-factory/audeze-home/slices/desktop-approach.png",
                        "imageAlt": "PRODUCTS"
                  },
                  {
                        "title": "Professional Audio",
                        "desc": "Professional Audio",
                        "description": "Professional Audio",
                        "icon": "shield",
                        "image": {
                              "src": "/assets/template-factory/audeze-home/slices/mobile-approach.png",
                              "alt": "Professional Audio"
                        },
                        "imageSrc": "/assets/template-factory/audeze-home/slices/mobile-approach.png",
                        "imageAlt": "Professional Audio"
                  },
                  {
                        "title": "Audiophile",
                        "desc": "Audiophile",
                        "description": "Audiophile",
                        "icon": "chart",
                        "image": {
                              "src": "/assets/template-factory/audeze-home/slices/mobile-approach.png",
                              "alt": "Audiophile"
                        },
                        "imageSrc": "/assets/template-factory/audeze-home/slices/mobile-approach.png",
                        "imageAlt": "Audiophile"
                  }
            ]
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        title: textField("Title"),
        subtitle: textField("Subtitle"),
      },
    },
    TemplateExclusiveAudezeHomeHomeSocialproofTestimonialsgridPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeHomeSocialproofTestimonialsgridPrimaryBlockModule, "TemplateExclusiveAudezeHomeHomeSocialproofTestimonialsgridPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeHomeSocialproofTestimonialsgridPrimary-1",
            "variant": "2col",
            "paddingY": "lg",
            "maxWidth": "xl",
            "title": "Building for world-class innovators",
            "items": [
                  {
                        "quote": "They curated a lifestyle, not only a space.",
                        "name": "Alexander Vane",
                        "role": "CEO",
                        "avatar": {
                              "src": "/assets/template-factory/audeze-home/slices/mobile-socialproof.png",
                              "alt": "Alexander Vane"
                        }
                  },
                  {
                        "quote": "A masterclass in restraint and elegance.",
                        "name": "Isabelle Dubois",
                        "role": "Founder",
                        "avatar": {
                              "src": "/assets/template-factory/audeze-home/slices/mobile-socialproof.png",
                              "alt": "Isabelle Dubois"
                        }
                  }
            ],
            "imageSrc": "/assets/template-factory/audeze-home/slices/desktop-socialproof.png",
            "imageAlt": "Results visual"
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        title: textField("Title"),
        imageSrc: textField("Imagesrc"),
        imageAlt: textField("Imagealt"),
      },
    },
    TemplateExclusiveAudezeHomeHomeCtaLeadcapturectaPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeHomeCtaLeadcapturectaPrimaryBlockModule, "TemplateExclusiveAudezeHomeHomeCtaLeadcapturectaPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeHomeCtaLeadcapturectaPrimary-1",
            "variant": "banner",
            "paddingY": "lg",
            "maxWidth": "xl",
            "title": "Uncompromised Audio",
            "subtitle": "Planar Magnetic Technology",
            "cta": {
                  "label": "Explore",
                  "href": "/blogs/audeze-artists/angie-randisi",
                  "variant": "primary"
            }
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        title: textField("Title"),
        subtitle: textField("Subtitle"),
      },
    },
    TemplateExclusiveAudezeHomeHomeFooterFooterPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeHomeFooterFooterPrimaryBlockModule, "TemplateExclusiveAudezeHomeHomeFooterFooterPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeHomeFooterFooterPrimary-1",
            "variant": "multiColumn",
            "paddingY": "md",
            "maxWidth": "xl",
            "logoText": "Audeze Headphones",
            "columns": [
                  {
                        "title": "Company",
                        "links": [
                              {
                                    "label": "Audiophile",
                                    "href": "/pages/audiophile"
                              },
                              {
                                    "label": "Professional",
                                    "href": "/collections/pro-audio"
                              },
                              {
                                    "label": "Gaming",
                                    "href": "/pages/gaming"
                              },
                              {
                                    "label": "Software",
                                    "href": "/pages/audeze-software"
                              },
                              {
                                    "label": "Accessories",
                                    "href": "/collections/accessories"
                              },
                              {
                                    "label": "Apparel",
                                    "href": "/collections/apparel"
                              },
                              {
                                    "label": "Accessibility Statement",
                                    "href": "/pages/accessibility-statement"
                              },
                              {
                                    "label": "About Audeze",
                                    "href": "/pages/about-us"
                              },
                              {
                                    "label": "Audeze",
                                    "href": "/"
                              }
                        ]
                  },
                  {
                        "title": "Legal",
                        "links": [
                              {
                                    "label": "Terms of Service",
                                    "href": "/policies/terms-of-service"
                              },
                              {
                                    "label": "Refund Policy",
                                    "href": "/policies/refund-policy"
                              },
                              {
                                    "label": "Shipping Policy",
                                    "href": "/policies/shipping-policy"
                              },
                              {
                                    "label": "Privacy Policy",
                                    "href": "/policies/privacy-policy"
                              },
                              {
                                    "label": "Cookie Policy",
                                    "href": "/pages/audeze-cookie-policy"
                              }
                        ]
                  }
            ],
            "legal": "© 2026 All rights reserved."
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        logoText: textField("Logotext"),
        legal: textField("Legal"),
      },
    },
    TemplateExclusiveAudezeHomeCollectionsAccessoriesNavigationNavbarPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeCollectionsAccessoriesNavigationNavbarPrimaryBlockModule, "TemplateExclusiveAudezeHomeCollectionsAccessoriesNavigationNavbarPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeCollectionsAccessoriesNavigationNavbarPrimary-1",
            "variant": "withCTA",
            "sticky": true,
            "paddingY": "sm",
            "maxWidth": "xl",
            "logo": "Audeze",
            "links": [
                  {
                        "label": "Home",
                        "href": "/",
                        "variant": "link"
                  },
                  {
                        "label": "Audeze",
                        "href": "/collections/accessories",
                        "variant": "link"
                  }
            ],
            "ctas": [
                  {
                        "label": "Explore",
                        "href": "/",
                        "variant": "primary"
                  }
            ]
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        sticky: booleanField("Sticky"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        logo: textField("Logo"),
      },
    },
    TemplateExclusiveAudezeHomeCollectionsAccessoriesHeroHerosplitPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeCollectionsAccessoriesHeroHerosplitPrimaryBlockModule, "TemplateExclusiveAudezeHomeCollectionsAccessoriesHeroHerosplitPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeCollectionsAccessoriesHeroHerosplitPrimary-1",
            "mediaPosition": "right",
            "paddingY": "lg",
            "headingSize": "md",
            "maxWidth": "xl",
            "title": "Audeze Headphones",
            "subtitle": "Explore Audeze solutions",
            "ctas": [
                  {
                        "label": "Explore",
                        "href": "/",
                        "variant": "primary"
                  }
            ],
            "background": "image",
            "backgroundMedia": {
                  "kind": "image",
                  "src": "/assets/template-factory/audeze-home/slices/desktop-hero.png",
                  "alt": "Audeze | Audeze Headphones reference"
            },
            "backgroundOverlay": "rgba(5,8,18,0.55)",
            "media": {
                  "kind": "image",
                  "src": "/assets/template-factory/audeze-home/slices/desktop-hero.png",
                  "alt": "Audeze | Audeze Headphones hero visual"
            }
      },
      fields: {
        id: textField("Id"),
        mediaPosition: textField("Mediaposition"),
        paddingY: textField("Paddingy"),
        headingSize: textField("Headingsize"),
        maxWidth: textField("Maxwidth"),
        title: textField("Title"),
        subtitle: textField("Subtitle"),
        background: textField("Background"),
        backgroundOverlay: textField("Backgroundoverlay"),
      },
    },
    TemplateExclusiveAudezeHomeCollectionsAccessoriesCtaLeadcapturectaPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeCollectionsAccessoriesCtaLeadcapturectaPrimaryBlockModule, "TemplateExclusiveAudezeHomeCollectionsAccessoriesCtaLeadcapturectaPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeCollectionsAccessoriesCtaLeadcapturectaPrimary-1",
            "variant": "banner",
            "paddingY": "lg",
            "maxWidth": "xl",
            "title": "Audeze",
            "subtitle": "Form Builder",
            "cta": {
                  "label": "Explore",
                  "href": "/",
                  "variant": "primary"
            }
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        title: textField("Title"),
        subtitle: textField("Subtitle"),
      },
    },
    TemplateExclusiveAudezeHomeCollectionsAccessoriesFooterFooterPrimary: {
      render: renderBlock(resolveBlockComponent(TemplateExclusiveAudezeHomeCollectionsAccessoriesFooterFooterPrimaryBlockModule, "TemplateExclusiveAudezeHomeCollectionsAccessoriesFooterFooterPrimary")),
      defaultProps: {
            "id": "TemplateExclusiveAudezeHomeCollectionsAccessoriesFooterFooterPrimary-1",
            "variant": "multiColumn",
            "paddingY": "md",
            "maxWidth": "xl",
            "logoText": "Audeze",
            "columns": [
                  {
                        "title": "Company",
                        "links": [
                              {
                                    "label": "Audiophile",
                                    "href": "/pages/audiophile"
                              },
                              {
                                    "label": "Professional",
                                    "href": "/collections/pro-audio"
                              },
                              {
                                    "label": "Gaming",
                                    "href": "/pages/gaming"
                              },
                              {
                                    "label": "Software",
                                    "href": "/pages/audeze-software"
                              },
                              {
                                    "label": "Accessories",
                                    "href": "/collections/accessories"
                              },
                              {
                                    "label": "Apparel",
                                    "href": "/collections/apparel"
                              },
                              {
                                    "label": "Accessibility Statement",
                                    "href": "/pages/accessibility-statement"
                              },
                              {
                                    "label": "About Audeze",
                                    "href": "/pages/about-us"
                              },
                              {
                                    "label": "Audeze",
                                    "href": "/"
                              }
                        ]
                  },
                  {
                        "title": "Legal",
                        "links": [
                              {
                                    "label": "Terms of Service",
                                    "href": "/policies/terms-of-service"
                              },
                              {
                                    "label": "Refund Policy",
                                    "href": "/policies/refund-policy"
                              },
                              {
                                    "label": "Shipping Policy",
                                    "href": "/policies/shipping-policy"
                              },
                              {
                                    "label": "Privacy Policy",
                                    "href": "/policies/privacy-policy"
                              },
                              {
                                    "label": "Cookie Policy",
                                    "href": "/pages/audeze-cookie-policy"
                              }
                        ]
                  }
            ],
            "legal": "© 2026 All rights reserved."
      },
      fields: {
        id: textField("Id"),
        variant: textField("Variant"),
        paddingY: textField("Paddingy"),
        maxWidth: textField("Maxwidth"),
        logoText: textField("Logotext"),
        legal: textField("Legal"),
      },
    },
};
